Move VAC ban settings to default_config.yml and allow whitelisted fla…
MarechJ/hll_rcon_tool pull request #279
Opened 2023-06-18 04:22 UTC by cemathey

* Move the VAC ban settings from `.env` to `default_config.yml`
* Allow whitelisted player flags to skip the VAC ban check
* Update unit tests to reflect changes

I did run the tests and add a couple more to reflect the changes and added some typing.

I did not test this against a real server with a real build, I don't know any VAC banned people to do any sort of real testing with.

I did not deprecate the environment variables from `.env` or any of the Docker files yet, if we do merge this we can do that in a later release once people have had time to update their settings.

Preferably we do the deprecation after we do PR 277 (if we merge/release that) so that we can change the `.env` file easier in future releases.

I'm not firing on all cylinders today but was knocking some stuff out, could use a thorough review to make sure I didn't miss anything stupid.

2023-06-25 22:28 UTC, timraay requested changes

2023-06-25 22:28 UTC, timraay commented on config/default_config.yml
> +VAC_GAME_BANS:
You should add some more comments here.

2023-06-25 22:28 UTC, timraay commented on config/default_config.yml
> +  steam_api_key: ""
Steam API key config key value should not be under the VAC game ban config. It should either be entirely separate or stay inside of the .env

2023-07-05 03:40 UTC, cemathey commented
The latest commits should cover the requested changes, I also added some better logging for steam API errors.

I accidentally rate limited myself while working on this with my steam API key, but we were swallowing those errors, now it should log a stack trace and people can see it happening.

2023-07-05 06:48 UTC, timraay approved these changes

2023-07-05 18:17 UTC, merged