Additional punishments for the BAN_TK_ON_CONNECT module
MarechJ/hll_rcon_tool pull request #64
Opened 2021-04-03 13:39 UTC by timraay

Allows server admins to choose different punishments for players that pass the TK threshold at the start of their session. See below file changes, should be pretty self-explanatory.

Particularly useful for server admins that don't want to accidently ban half of the server at the start of an event.

Note that I haven't been able to test these changes yet.

2021-04-03 13:45 UTC, MarechJ requested changes
Looks ok, except for the danger of the ban duration being a string.

If you motivation for adding that it competitive matches the best way would be to add a toggle in the UI though

2021-04-03 13:45 UTC, MarechJ commented on rcon/game_logs.py
> +    ban_duration = config.get("ban_duration_in_hours", 0)
You probably want to try to cast that to an `int()` :)

2021-04-04 09:09 UTC, timraay commented
I would also have added a toggle in the UI, but I have no experience with JS whatsoever.

Anyway, I've made the requested changes. It should now handle invalid ban durations and default to 0.

2021-04-05 12:48 UTC, MarechJ approved these changes

2021-04-05 12:48 UTC, MarechJ commented
Please test and merge if it's fine :)

2021-04-24 18:01 UTC, MarechJ commented
Were you able to test?

2023-05-10 20:28 UTC, closed without merging